LOG_PATH: "logs"
DATA_PATH: "data/books"
CHROMA_DB_PATH: "chromadb"
CHROMA_DB_FILE: "chroma.sqlite3"
# EMBEDDING_MODEL_NAME: "all-MiniLM-L6-v2"
EMBEDDING_MODEL_NAME: "intfloat/multilingual-e5-large-instruct"
# GENERATION_MODEL_NAME: "Qwen/Qwen3-0.6B"
GENERATION_MODEL_NAME: "Qwen/Qwen1.5-1.8B"
CHUNK_SIZE: 1000
CHUNK_OVERLAP: 500
