LOG_PATH: "logs"
DATA_PATH: "data/books"
CHROMA_DB_PATH: "chromadb"
CHROMA_DB_FILE: "chroma.sqlite3"
MODEL_NAME: "intfloat/multilingual-e5-large-instruct"
# MODEL_NAME: "all-MiniLM-L6-v2"
CHUNK_SIZE: 1000
CHUNK_OVERLAP: 500
